// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/getSmscd/getSmscd.proto

package go_micro_srv_getSmscd

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Uuid                 string   `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0892cf804cfa06a, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Request) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Request) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type Response struct {
	Errno                string   `protobuf:"bytes,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Errmsg               string   `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0892cf804cfa06a, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *Response) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "go.micro.srv.getSmscd.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.getSmscd.Response")
}

func init() { proto.RegisterFile("proto/getSmscd/getSmscd.proto", fileDescriptor_e0892cf804cfa06a) }

var fileDescriptor_e0892cf804cfa06a = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2d, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0x4f, 0x2d, 0x09, 0xce, 0x2d, 0x4e, 0x4e, 0x81, 0x33, 0xf4, 0xc0, 0xe2, 0x42,
	0xa2, 0xe9, 0xf9, 0x7a, 0xb9, 0x99, 0xc9, 0x45, 0xf9, 0x7a, 0xc5, 0x45, 0x65, 0x7a, 0x30, 0x49,
	0x25, 0x77, 0x2e, 0xf6, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x11, 0x2e, 0xd6, 0x82,
	0x8c, 0xfc, 0xbc, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x08, 0x47, 0x48, 0x88, 0x8b,
	0xa5, 0x24, 0xb5, 0xa2, 0x44, 0x82, 0x09, 0x2c, 0x08, 0x66, 0x83, 0xc4, 0x4a, 0x4b, 0x33, 0x53,
	0x24, 0x98, 0x21, 0x62, 0x20, 0xb6, 0x92, 0x05, 0x17, 0x47, 0x50, 0x6a, 0x71, 0x41, 0x7e, 0x5e,
	0x71, 0x2a, 0xc8, 0xa4, 0xd4, 0xa2, 0xa2, 0xbc, 0x7c, 0x98, 0x49, 0x60, 0x8e, 0x90, 0x18, 0x17,
	0x5b, 0x6a, 0x51, 0x51, 0x6e, 0x71, 0x3a, 0xd4, 0x2c, 0x28, 0xcf, 0x28, 0x94, 0x8b, 0xc3, 0x1d,
	0xea, 0x1c, 0x21, 0x4f, 0x2e, 0x16, 0xe7, 0xc4, 0x9c, 0x1c, 0x21, 0x39, 0x3d, 0xac, 0xce, 0xd5,
	0x83, 0xba, 0x55, 0x4a, 0x1e, 0xa7, 0x3c, 0xc4, 0x09, 0x4a, 0x0c, 0x49, 0x6c, 0x60, 0x7f, 0x1b,
	0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xc9, 0xf5, 0xeb, 0x6f, 0x18, 0x01, 0x00, 0x00,
}
