// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/getSmscd/getSmscd.proto

package go_micro_srv_getSmscd

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for GetSmscd service

type GetSmscdService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type getSmscdService struct {
	c    client.Client
	name string
}

func NewGetSmscdService(name string, c client.Client) GetSmscdService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.getSmscd"
	}
	return &getSmscdService{
		c:    c,
		name: name,
	}
}

func (c *getSmscdService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "GetSmscd.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GetSmscd service

type GetSmscdHandler interface {
	Call(context.Context, *Request, *Response) error
}

func RegisterGetSmscdHandler(s server.Server, hdlr GetSmscdHandler, opts ...server.HandlerOption) error {
	type getSmscd interface {
		Call(ctx context.Context, in *Request, out *Response) error
	}
	type GetSmscd struct {
		getSmscd
	}
	h := &getSmscdHandler{hdlr}
	return s.Handle(s.NewHandler(&GetSmscd{h}, opts...))
}

type getSmscdHandler struct {
	GetSmscdHandler
}

func (h *getSmscdHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.GetSmscdHandler.Call(ctx, in, out)
}
