// Code generated by protoc-gen-go. DO NOT EDIT.
// source: postRet.proto

package go_micro_srv_postRet

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	SmsCode              string   `protobuf:"bytes,3,opt,name=sms_code,json=smsCode,proto3" json:"sms_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_d277bf2a4bc0507d, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *Request) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Request) GetSmsCode() string {
	if m != nil {
		return m.SmsCode
	}
	return ""
}

type Response struct {
	Errno                string   `protobuf:"bytes,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Errmsg               string   `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_d277bf2a4bc0507d, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *Response) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "go.micro.srv.postRet.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.postRet.Response")
}

func init() { proto.RegisterFile("postRet.proto", fileDescriptor_d277bf2a4bc0507d) }

var fileDescriptor_d277bf2a4bc0507d = []byte{
	// 197 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xbd, 0x6b, 0xc3, 0x30,
	0x10, 0x47, 0xeb, 0x7e, 0xd8, 0xee, 0x41, 0x17, 0x61, 0x8a, 0x6b, 0x68, 0x29, 0x9e, 0x3a, 0x69,
	0x68, 0x96, 0xec, 0x1e, 0xb2, 0x06, 0x4d, 0xd9, 0x82, 0x3f, 0x0e, 0x63, 0xb0, 0x7c, 0xca, 0x9d,
	0x92, 0xfc, 0xfb, 0x21, 0xb6, 0xc8, 0x94, 0x8c, 0x8f, 0x07, 0xf7, 0x7b, 0x1c, 0x7c, 0x38, 0x12,
	0x6f, 0xd0, 0x6b, 0xc7, 0xe4, 0x49, 0x65, 0x3d, 0x69, 0x3b, 0xb4, 0x4c, 0x5a, 0xf8, 0xa4, 0x83,
	0x2b, 0x77, 0x90, 0x18, 0x3c, 0x1c, 0x51, 0xbc, 0xfa, 0x84, 0xd8, 0x52, 0x33, 0x8c, 0x98, 0x47,
	0xbf, 0xd1, 0xdf, 0xbb, 0x09, 0xa4, 0x0a, 0x48, 0x5d, 0x2d, 0x72, 0x26, 0xee, 0xf2, 0xe7, 0xd9,
	0xdc, 0x58, 0x7d, 0x41, 0x2a, 0x56, 0xf6, 0x2d, 0x75, 0x98, 0xbf, 0xcc, 0x2e, 0x11, 0x2b, 0x15,
	0x75, 0x58, 0xae, 0x21, 0x35, 0x28, 0x8e, 0x26, 0x41, 0x95, 0xc1, 0x1b, 0x32, 0x4f, 0x14, 0x2e,
	0x2f, 0x70, 0x1d, 0x44, 0x66, 0x2b, 0x7d, 0x38, 0x1b, 0xe8, 0xdf, 0x40, 0xb2, 0x5d, 0xf2, 0xd4,
	0x06, 0x5e, 0xab, 0x7a, 0x1c, 0xd5, 0xb7, 0xbe, 0x57, 0xaf, 0x43, 0x7a, 0xf1, 0xf3, 0x48, 0x2f,
	0xfb, 0xe5, 0x53, 0x13, 0xcf, 0x4f, 0x58, 0x5d, 0x02, 0x00, 0x00, 0xff, 0xff, 0x70, 0x29, 0xf0,
	0x47, 0x15, 0x01, 0x00, 0x00,
}
